# Site settings
title: Dano Marr
email: danomarr@gmail.com
description: My digital journal. Where I write about things I find interesting like art, organization design, and Dungeons &amp; Dragons. As a discipline, I keep trying to find better questions to ask.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://danomarr.gibhub.io" # the base hostname & protocol for your site
twitter_username: danomarr
github_username:  danomarr

# Build settings
markdown: kramdown
